### ISSUE TITLE
NumFocus fiscal sponsorship

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/community#21]
There has been general support for the idea that applying for [numfocus fiscal sponsorship](https://numfocus.org/information-fiscal-sponsorship) would be a good route for Zarr. This issue is a place to capture/share/coordinate around making an application.

**Comment by alimanfoo** [comment]
Just to mention that I emailed Leah Silen at NumFocus today to open a discussion, will feed back any info.

**Comment by jrbourbeau** [comment]
Dask [just went through](https://github.com/dask/governance/issues/1) the process of applying for NumFOCUS fiscal sponsorship, so I thought I'd post here with some relevant information. The requirements for fiscal sponsorship are:

- [ ] Release its code under an OSI approved open source license (exceptions must be approved by the NumFOCUS Board of Directors)
- [ ] Have a Code of Conduct, either adopted from our own or similar in spirit.
- [ ] Have a community that is active and of reasonable size
- [ ] Have multiple people willing to sign the Fiscal Sponsorship Agreement (5 signatories for a comprehensive FSA; 3 signatories for a grantor-grantee FSA). Those people must be active in the project; one person may be an external stakeholder instead of a project contributor.​
- [ ] Have a leadership body or team consisting of at least 3 people; these people should not be employed by the same entity or share a common affiliation beyond that of the project.

and the application template is at https://docs.google.com/document/d/1-MwAqOir5vf4FAhREPj80Ynv-SKugSaN5mZcIHUIsug/edit

**Comment by alimanfoo** [comment]
Just to mention that we (@ryan-williams, @joshmoore, @alimanfoo, @jakirkham) are in the process of submitting the application for numfocus fiscal sponsorship. @zarr-developers/core-devs please let us know if there are any objections.

There is also discussion of whether the grantor/grantee model or the comprehensive model of fiscal sponsorship is more appropriate. We are submitting both applications and discussing with numfocus which is better. Personally I feel the comprehensive model would be better because it provides greater protections for project contributors, but I am no expert in these matters and would be very happy to take advice. If you have any preference please let us know.

**Comment by joshmoore** [comment]
Consider this well underway! Closing.
